#!/usr/bin/python3
import os, os.path

class color:
   PURPLE = '\033[95m'
   CYAN = '\033[96m'
   DARKCYAN = '\033[36m'
   BLUE = '\033[94m'
   GREEN = '\033[92m'
   YELLOW = '\033[93m'
   RED = '\033[91m'
   BOLD = '\033[1m'
   UNDERLINE = '\033[4m'
   END = '\033[0m'

def printW(pwr):
    if pwr < 10:
        print('  ', end='')
        print(str(pwr).ljust(4,'0').ljust(4), end=' W')
    elif pwr < 100:
        print(' ', end='')
        print(str(pwr).ljust(5,'0').ljust(5), end=' W')
    else:
        print(str(pwr).ljust(6,'0').ljust(6), end=' W')

rows,columns = os.popen('stty size', 'r').read().split()

powerpath = '/sys/class/power_supply'
batpath = powerpath + '/BAT'
pathes = ['energy_full_design', 'energy_full', 'energy_now', 'power_now']

pwrvals = []
totals = [0, 0, 0, 0]

print()
batcount = len([name for name in os.listdir(powerpath) if name.startswith('BAT')])
for b in range(batcount):
    print('BAT'+str(b)+':')
    pwrvals.append([])
    for p in pathes:
        file = open(batpath + str(b) + '/' + p, 'r')
        pwr = round(float(file.readline()) / 1000000, 2)
        pwrvals[b].append(pwr)
        
        print((p+': ').ljust(30), end='')
        printW(pwr)
        if p != "power_now": print('h')
    print('\n')

for b in range(batcount):
    for i in range(len(pathes)):
        totals[i] = round(totals[i] + pwrvals[b][i], 2)

print('-'.ljust(39, '-'))
print('\nTotal:')
for i in range(len(pathes)):
    print((pathes[i]+': ').ljust(30), end='')
    printW(totals[i])
    if p != "power_now": print('h')
    print('')

print()
