#!/bin/sh
if [[ -z "$1" ]]; then
    echo "Usage: $0 <number of images> [<basename>]"
    exit -1
fi

n="$1"
basename="$2"
[[ ! -z "$basename" ]] && basename="$basename"_
for i in $(seq 1 1 $n); do
    read -n 1 -r -s -p $'Press enter to continue...\n'
    scanimage --resolution 300 --format=png -o "$basename""$i"".png"
done
