#!/bin/sh
directory="$HOME/Nextcloud/Pictures/Screenshots/"
time="$(date +%F_%H_%M_%S)"
filename="$(newfilename $directory$time png)"

if [[ "$1" == "f" ]]; then
    #scrot -m $filename -e 'xclip -selection c -t image/png < $f'
    spectacle -fbco $filename
    echo "Screenshot saved to $filename."
elif [[ "$1" == "a" ]]; then
    spectacle -abco $filename
    #scrot -ub $filename -e 'xclip -selection c -t image/png < $f'
    echo "Screenshot saved to $filename."
elif [[ "$1" == "r" ]]; then
    #spectacle -rbc
    sleep 0.2 && flameshot gui
    echo "Screenshot saved to clipboard."
fi

exit
# lol fuq u this barely worked anyway

touch $filename
echo "$filename set as screenshot file name, placeholder created"
echo "Capturing screenshot"
spectacle -$1bno $filename &
spec_pid=$!
inotifywait -qm --event close_write,moved_to --format "%w%f" "$directory" | while read screenshot
do
    if [ -f "$screenshot" ]; then
        if [ "$filename" == "$screenshot" ]; then
            kill $spec_pid
            echo "$screenshot created!"
            echo "Copying to clipboard..."
            cat $filename | xclip -i -selection clipboard -t image/png
            echo "Done! Exiting..."
            kill -- -$$
        fi
    fi
done
