#!/bin/sh
sudo systemctl stop ModemManager
echo 0 | sudo tee /sys/bus/usb/devices/1-3/bConfigurationValue
echo 3 | sudo tee /sys/bus/usb/devices/1-3/bConfigurationValue
sudo systemctl start ModemManager
